import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';import vm from 'node:vm';
const source=fs.readFileSync(new URL('../background.js',import.meta.url),'utf8');
function fn(name){const m=new RegExp(`(?:async )?function ${name}\\(`).exec(source);assert.ok(m,name);const end=source.indexOf('\n}\n',m.index);assert.ok(end>m.index,name);return source.slice(m.index,end+2)}
const AT=Date.parse('2026-09-07T13:00:00Z');
const ROSTER={iherb:['photopochtoy@gmail.com','questburgh@gmail.com','oksanasorokapocht@gmail.com'],ebay:['ipochtoy@gmail.com'],amazon:['ipochtoy@gmail.com','photopochtoy@gmail.com']};
function harness(){const store={trackScreenshotQueue:[]},writes=[],clock={now:AT};class Clock extends Date{constructor(...a){super(...(a.length?a:[clock.now]))}static now(){return clock.now}}
 const context=vm.createContext({Date:Clock,Intl,console,Promise,Set,Object,Number,String,Math,JSON,
 chrome:{storage:{local:{get:async keys=>Object.fromEntries((Array.isArray(keys)?keys:[keys]).filter(k=>k in store).map(k=>[k,structuredClone(store[k])])),set:async values=>{writes.push(structuredClone(values));Object.assign(store,structuredClone(values))}}}},
 readParserRejectedUploadProof:async()=>null,loadAccountsConfig:async()=>({}),buildExpectedPipelineRoster:()=>structuredClone(ROSTER)});
 const names=['getNextDailyRun','getLastDailyRunSlot','nightCabinetSlotId','nightCabinetLeaseSlotIds','nightCabinetSlotDay','nightCabinetNativeAdmissionAt','inspectNightCabinetLease','withNightCabinetLeaseWrite','nightCabinetTerminalProof','nightCabinetTerminalSlotProof','storeWalkParserIdleProof','inspectManualControlEnvelope','manualControlEnvelopeEqual','manualControlTokenAllowed','manualControlTransitionProof','manualControlParserStartProof','inspectNightCabinetTransitionRequest','nightCabinetTransitionAllowed','handleNightCoordinatorLeaseTransitionRequest','prepareParserNightCabinetLease','externalCoordinatorStartDecision','createPipelineRun','handleExternalControlRequest'];
 vm.runInContext(source.slice(0,source.indexOf('let dailyDiagnosticWriteQueue'))+'\nlet nightCabinetLeaseWriteChain=Promise.resolve();\n'+names.map(fn).join('\n'),context);
 // Only browser dispatch/run body is simulated. Both public handlers, CAS,
 // lease consumer and durable pipeline creation below execute actual source.
 context.runDailyAutoParse=async(sourceName,options)=>{const proof=await context.prepareParserNightCabinetLease({...options,now:clock.now});if(!proof.ok)return false;const run=await context.createPipelineRun(sourceName,proof.lease);store.pipelineRun={...run,status:'running',startedAt:clock.now};store.pipelineStage={runId:run.id,active:true,stages:['iherb','ebay','amazon','done'],stageName:'iherb',currentIndex:0};return true};
 const id=crypto.randomUUID(),envelope={schemaVersion:1,kind:'manual-control',id,requestSha:'a'.repeat(64),coordinatorRunId:crypto.randomUUID(),createdAt:AT,deadlineAt:AT+6*3600000,nextNativeAdmissionAt:Date.parse('2026-09-08T00:30:00Z')};
 const desired=(owner,phase,suffix)=>({slotId:String(AT),owner,phase,token:`control:${id}:${suffix}`});
 const transition=async(d,e=envelope)=>{const current=store.nightCabinetLease;store.nightCoordinatorLeaseTransitionRequest={requestId:'request-'+crypto.randomUUID(),requestedAt:clock.now,expected:current?{state:'present',slotId:current.slotId,owner:current.owner,phase:current.phase,token:current.token,...(current.runId?{runId:current.runId}:{})}:{state:'missing'},desired:d,...(e===undefined?{}:{manualControl:e})};return context.handleNightCoordinatorLeaseTransitionRequest()};
 const key=`manualControlGeneration:${id}`;
 const ready=async()=>{assert.equal((await transition(desired('store-walk','store-main','main'))).ok,true);assert.equal((await transition(desired('store-walk','completed','main'))).ok,true);assert.equal((await transition(desired('parser','ready','parser-1'))).ok,true)};
 const start=async()=>{store.externalControlRequest={action:'start_pipeline',requestedAt:++clock.now,slotId:String(AT),token:`control:${id}:parser-1`};return context.handleExternalControlRequest()};
 const terminal=()=>{const run=store.pipelineRun;Object.assign(run,{status:'completed',finishedAt:clock.now,completed:structuredClone(ROSTER)});store.pipelineStage={runId:run.id,active:false,stages:['iherb','ebay','amazon','done'],stageName:'done',currentIndex:3};Object.assign(store,{trackScreenshotQueue:[],screenshotQueueBlocked:null,pendingSheetsUpload:null,lastSheetsUploadRunId:run.id,lastSheetsUploadOkAt:clock.now})};
 return{store,writes,clock,context,envelope,id,key,desired,transition,ready,start,terminal};
}
test('full actual manual handoff→external start→durable one Parser→terminal handoff',async()=>{const h=harness();await h.ready();assert.equal(h.store[h.key].parserRunId,null);assert.equal((await h.start()).result.ok,true);const id=h.store.pipelineRun.id;assert.equal(h.store[h.key].parserRunId,id);assert.equal(h.store.pipelineRun.slotAt,AT);assert.equal(h.store.pipelineRun.nightSlotDay,'2026-09-07');assert.equal(h.store.pipelineRun.source,'coordinator-control');h.terminal();assert.equal((await h.transition(h.desired('store-walk','store-catchup','catchup-1'))).ok,true);assert.equal(h.store[h.key].parserRunId,id);assert.deepEqual(h.store[h.key].envelope,h.envelope)});
test('native allowed slots and original request shape remain unchanged; no manual record created',async()=>{const h=harness();const d={slotId:h.context.nightCabinetLeaseSlotIds(AT)[0],owner:'store-walk',phase:'store-main',token:'native-store-token0001'};const req={requestId:'native-'+crypto.randomUUID(),requestedAt:AT,expected:{state:'missing'},desired:d};h.store.nightCoordinatorLeaseTransitionRequest=req;assert.equal((await h.context.handleNightCoordinatorLeaseTransitionRequest()).ok,true);assert.equal(h.store.manualControlGenerationIndex,undefined);assert.deepEqual(Object.keys(h.store.nightCabinetLease).sort(),['expires','heartbeat','owner','phase','slotId','token'])});
for(const bad of ['absent','null','hash','extra','foreign-id','future','expired','native-overlap','token'])test('manual envelope '+bad+' refuses before issuing lease/record',async()=>{const h=harness();const e={...h.envelope},d=h.desired('store-walk','store-main','main');if(bad==='hash')e.requestSha='bad';if(bad==='extra')e.force=true;if(bad==='foreign-id')e.id=crypto.randomUUID();if(bad==='future')e.createdAt=AT+1;if(bad==='expired')h.clock.now=e.deadlineAt;if(bad==='native-overlap')e.deadlineAt=e.nextNativeAdmissionAt;if(bad==='token')d.token='foreign-token-0001';h.store.nightCoordinatorLeaseTransitionRequest={requestId:'request-'+crypto.randomUUID(),requestedAt:h.clock.now,expected:{state:'missing'},desired:d,...(bad==='absent'?{}:{manualControl:bad==='null'?null:e})};const r=await h.context.handleNightCoordinatorLeaseTransitionRequest();assert.equal(r.ok,false);assert.equal(h.store.nightCabinetLease,undefined);assert.equal(h.store[h.key],undefined);assert.equal(h.writes.length,0)});
test('changed immutable request hash or malformed prior record cannot progress owner',async()=>{for(const kind of ['hash','record','index']){const h=harness();await h.transition(h.desired('store-walk','store-main','main'));const before=structuredClone(h.store.nightCabinetLease);if(kind==='hash')h.envelope.requestSha='b'.repeat(64);if(kind==='record')h.store[h.key].parserRunId=4;if(kind==='index')h.store.manualControlGenerationIndex=false;const r=await h.transition(h.desired('store-walk','completed','main'));assert.equal(r.ok,false);assert.deepEqual(h.store.nightCabinetLease,before)}});
test('foreign active generation refuses manual admission without allocating a record',async()=>{const h=harness();h.store.nightCabinetLease={slotId:String(AT-86400000),owner:'store-walk',phase:'running',token:'foreign-store-token0001',heartbeat:AT,expires:AT+900000};const old=structuredClone(h.store.nightCabinetLease);const r=await h.transition(h.desired('store-walk','store-main','main'));assert.equal(r.ok,false);assert.deepEqual(h.store.nightCabinetLease,old);assert.equal(h.store[h.key],undefined)});
test('one Parser attempt persists even if ready lease is falsely reintroduced; no second pipeline mutation',async()=>{const h=harness();await h.ready();const ready=structuredClone(h.store.nightCabinetLease);await h.start();const original=structuredClone(h.store.pipelineRun),n=h.writes.length;h.store.nightCabinetLease=ready;await assert.rejects(h.context.createPipelineRun('coordinator-control',ready),/attempt unavailable/);assert.equal(JSON.stringify(h.store.pipelineRun),JSON.stringify(original));assert.equal(h.writes.length,n)});
test('parallel duplicate pipeline calls serialize: exactly one wins',async()=>{const h=harness();await h.ready();const lease=structuredClone(h.store.nightCabinetLease);const results=await Promise.allSettled([h.context.createPipelineRun('coordinator-control',lease),h.context.createPipelineRun('coordinator-control',lease)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(h.writes.filter(v=>v.pipelineRun).length,1)});
test('record and running lease commit atomically; quota/write failure does not consume a phantom run',async()=>{const h=harness();await h.ready();const lease=structuredClone(h.store.nightCabinetLease);h.context.chrome.storage.local.set=async()=>{throw Error('QUOTA_BYTES')};await assert.rejects(h.context.createPipelineRun('coordinator-control',lease),/QUOTA_BYTES/);assert.equal(h.store[h.key].parserRunId,null);assert.equal(h.store.pipelineRun,undefined);assert.equal(h.store.nightCabinetLease.phase,'ready')});
test('work reserve forbids new start/catchup while allowing same-token terminal cleanup only',async()=>{const h=harness();await h.ready();h.clock.now=h.envelope.deadlineAt-900000;Object.assign(h.store.nightCabinetLease,{heartbeat:h.clock.now,expires:h.clock.now+900000});await assert.rejects(h.context.createPipelineRun('coordinator-control',h.store.nightCabinetLease),/attempt unavailable/);const other=harness();await other.transition(other.desired('store-walk','store-main','main'));other.clock.now=other.envelope.deadlineAt-900000;Object.assign(other.store.nightCabinetLease,{heartbeat:other.clock.now-1,expires:other.clock.now+900000});assert.equal((await other.transition(other.desired('store-walk','completed','main'))).ok,true);assert.equal((await other.transition(other.desired('parser','ready','parser-1'))).ok,false)});
test('terminal handoff requires exact queue/Sheets/run: pending, stale or foreign receipt never transfers',async()=>{for(const kind of ['queue','pending','run','receipt']){const h=harness();await h.ready();await h.start();h.terminal();if(kind==='queue')h.store.trackScreenshotQueue=[{}];if(kind==='pending')h.store.pendingSheetsUpload={};if(kind==='run')h.store.pipelineStage.runId='foreign';if(kind==='receipt')h.store.lastSheetsUploadRunId='foreign';const r=await h.transition(h.desired('store-walk','store-catchup','catchup-1'));assert.equal(r.ok,false);assert.equal(h.store.nightCabinetLease.owner,'parser')}});
test('next native 21:00 generation uses native slots and expired exact completed manual lease normally',async()=>{const h=harness();await h.ready();await h.start();h.terminal();await h.transition(h.desired('store-walk','store-catchup','catchup-1'));await h.transition(h.desired('store-walk','completed','catchup-1'));const manual=structuredClone(h.store[h.key]);h.clock.now=Date.parse('2026-09-08T01:00:00Z');const slots=h.context.nightCabinetLeaseSlotIds(h.clock.now);assert.ok(slots.includes(String(Date.parse('2026-09-08T03:00:00Z'))));const current=h.store.nightCabinetLease;h.store.nightCoordinatorLeaseTransitionRequest={requestId:'native-'+crypto.randomUUID(),requestedAt:h.clock.now,expected:{state:'present',slotId:current.slotId,owner:current.owner,phase:current.phase,token:current.token},desired:{slotId:slots.at(-1),owner:'store-walk',phase:'store-main',token:'native-next-token0001'}};assert.equal((await h.context.handleNightCoordinatorLeaseTransitionRequest()).ok,true);assert.deepEqual(h.store[h.key],manual)});
test('unknown post-write reply still leaves one consumed attempt and never writes a second run',async()=>{const h=harness();await h.ready();const lease=structuredClone(h.store.nightCabinetLease),set=h.context.chrome.storage.local.set;h.context.chrome.storage.local.set=async values=>{await set(values);if(values.pipelineRun)throw Error('disconnect after commit')};await assert.rejects(h.context.createPipelineRun('coordinator-control',lease),/disconnect/);const runId=h.store.pipelineRun.id;assert.equal(h.store[h.key].parserRunId,runId);h.store.nightCabinetLease=lease;await assert.rejects(h.context.createPipelineRun('coordinator-control',lease),/attempt unavailable/);assert.equal(h.writes.filter(v=>v.pipelineRun).length,1)});
test('manual admission never rewrites existing raw arrays, observed timestamps or ACK references',async()=>{const h=harness();Object.assign(h.store,{orderData:{amazon:[{order:'exact',qty:null,observed_at:'original'},{order:'exact',qty:2,observed_at:'original'}]},screenshotArchiveLedger:{old:{message_id:17}},sentScreenshots:{old:true}});const before=JSON.stringify([h.store.orderData,h.store.screenshotArchiveLedger,h.store.sentScreenshots]);await h.transition(h.desired('store-walk','store-main','main'));assert.equal(JSON.stringify([h.store.orderData,h.store.screenshotArchiveLedger,h.store.sentScreenshots]),before);assert.ok(h.writes.every(v=>!Object.keys(v).some(k=>['orderData','screenshotArchiveLedger','sentScreenshots'].includes(k))))});
test('partial index/record pairs and full ledger cannot be silently rebuilt or truncated',async()=>{for(const kind of ['index-only','record-only','full','malformed']){const h=harness();if(kind==='index-only')h.store.manualControlGenerationIndex=[h.id];if(kind==='record-only')h.store[h.key]={schemaVersion:1,envelope:h.envelope,admittedAt:AT,parserRunId:null};if(kind==='full')h.store.manualControlGenerationIndex=Array.from({length:64},()=>crypto.randomUUID());if(kind==='malformed')h.store.manualControlGenerationIndex=['-'.repeat(36)];const before=JSON.stringify(h.store);const r=await h.transition(h.desired('store-walk','store-main','main'));assert.equal(r.ok,false,kind);assert.equal(h.store.nightCabinetLease,undefined);assert.equal(h.writes.some(v=>v.manualControlGenerationIndex),false);assert.equal(JSON.stringify(Object.fromEntries(Object.entries(h.store).filter(([k])=>!k.startsWith('nightCoordinator')&&!k.startsWith('lastHandled')))),before)}});
